### ISSUE TITLE
(August) Add "Create New Event" Option to Event Creation/Workflow?

### ISSUE THREAD

**Issue by curtiskphsc** [phsc-edu/2018#230] opened 2018-05-17 16:22 UTC
We had what I feel is a good suggestion come in from Jackie Eden. She created a new event and when completed she wanted to immediately create another event but could not figure out how. Currently the only way I am aware that this can be accomplished is to go back to the dashboard and start from the beginning. I am suggesting that a "New Event" or "Create New Event" option be added so content creators do not have to return to the dashboard. I have provided a mock up. Clicking the link would take the user directly to https://career-services.phsc.edu/node/add/even with URL dependant on the sub domain of course.
![new-event-idea](https://user-images.githubusercontent.com/28155245/40190310-98e5d1f4-59cc-11e8-97aa-bb4f49e64984.JPG)
![new-event-idea-2](https://user-images.githubusercontent.com/28155245/40190312-98fa6aa6-59cc-11e8-9e48-f35ad06928b8.JPG)

Is this possible?

**Comment by curtiskphsc** [comment] 2018-07-30 12:34
@jeppy64 @C13L0 As the original request was from a sub domain user, and this would not work for sub domains, I would like to speak with Melissa Rushton and her staff as they are tasked with adding events to the main site, and changing any of their current processes without consulting them would be unfair. I will get back to you soon on this. For now, just hold off.

**Comment by curtiskphsc** [comment] 2018-07-30 13:46
@jeppy64 @C13L0 @boettcc Upon discussion with Melissa Rushton, after she reviewed the ticket and idea, she states it would save her staff a great deal of time when entering a large number of events which they do often from what I understand. I am good with moving forward on this, as Jay has outlined in his comments above, at the convenience of the parties affected. This is not a high priority on my end.

**Comment by C13L0** [comment] 2018-07-30 16:06
@jeppy64 addanother module has been pushed to marketing website.

**Comment by jeppy64** [comment] 2018-07-31 02:47
@curtiskphsc  @C13L0 

Add another has been configured on the live marketing site for only the Event content type (explicitly disabled for all other content types). Upon entering a new event, at the bottom of the screen there's now a new button named "Save and Add Another". Clicking this will commit the current node add and redirect back to node/add/even

Time to complete: 1/2 hour

**Comment by C13L0** [comment] 2018-07-31 13:14
@jeppy64 I am getting an error when using the "Save and add another"

Steps to reproduce:

1. Logged in as Event Editor
2. Added information into all required fields, including an end date
3. Choose Save and add another button

This results in an error message "This value should not be null."

![value-should-not-be-null](https://user-images.githubusercontent.com/3138019/43461728-2cc905f2-94a2-11e8-84ac-5f14284a8553.png)

**Comment by C13L0** [comment] 2018-07-31 13:27
@jeppy64 Actually, I can't add any new event.

![entity-label](https://user-images.githubusercontent.com/3138019/43462397-fcd45dae-94a3-11e8-8445-9f116eb0a371.png)

**Comment by jeppy64** [comment] 2018-08-01 12:24
@C13L0 

It looks like in the new event - to -event_day entity reference field, cache was wreaking havoc and then, configuration had turned off the default value of "Published" on an Event Day and Session bundles. The error you were seeing was the result of the Event Day not being able to be saved with autolabel on the time/date stamp of the Event Day due to the configuration default not being "Published".

Please try it again just as you had.

**Comment by jeppy64** [comment] 2018-08-01 16:08
@curtiskphsc  @C13L0 

Unfortunately the Addanother module cannot handle entity references. We have a definite one (potentially two) entity references from the Event that deal with dates/times: 

One Event - can have many Event Days (entity reference number 1) <-- at least 1 mandatory
One Event Day - can have many sessions (entity reference number 2) <-- not mandatory

So, when saving your event day is where the Addanother module broke down due to the entity reference.

Recommend removing this module from the codebase. I'll keep an eye out for a module that will work for us on the main site.

**Comment by C13L0** [comment] 2018-08-07 12:37
@jeppy64 Thank you for the work you put into this. Closing ticket.

**Closed by C13L0** 2018-08-07 12:37 UTC
Labels: Work Order, phsc.edu
